[technote]
id = "CTN-3"
series_id = "CTN"
canonical_url = "https://ctn-003.lsst.io"
github_url = "https://github.com/lsst/ctn-003"
github_default_branch = "main"
date_created = 2025-06-08T22:55:02Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Yousuke"
name.family = "Utsumi"
internal_id = "utsumiy"
orcid = "0000-0001-6161-8988"
[[technote.authors.affiliations]]
name = "National Astronomical Observatory of Japan"
internal_id = "NAOJ"
address = "2-21-1 Osawa, Mitaka, Tokyo 181-8588, Japan"
