[technote]
id = "CTN-003"
series_id = "CTN"
canonical_url = "https://ctn-003.lsst.io"
github_url = "https://github.com/lsst/ctn-003"
github_default_branch = "main"
date_created = 2025-06-08T22:55:02Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
internal_id = "utsumiy"
orcid = "https://orcid.org/0000-0001-6161-8988"
name = {given = "Yousuke", family = "Utsumi"}

[[technote.authors.affiliations]]
name = "National Astronomical Observatory of Japan"
internal_id = "NAOJ-Chile"
address = "Chile Observatory, Los Abedules 3085, Vitacura, Santiago, Chile"
[[technote.authors]]
name.given = "Theo"
name.family = "Shutt"

[[technote.authors]]
name.given = "Shuang"
name.family = "Laing"

[[technote.authors]]
name.given = "Stuart"
name.family = "Marshall"

[[technote.authors]]
name.given = "Tony"
name.family = "Johnson"

[[technote.authors]]
name.given = "Steve"
name.family = "Tether""

[[technote.authors]]
name.given = "Julio"
name.family = "Constanzo "
