[technote]
id = "CTN-003"
series_id = "CTN"
canonical_url = "https://ctn-003.lsst.io"
github_url = "https://github.com/lsst/ctn-003"
github_default_branch = "main"
date_created = 2025-06-08T22:55:02Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
internal_id = "utsumiy"
orcid = "https://orcid.org/0000-0001-6161-8988"
name = {given = "Yousuke", family = "Utsumi"}

[[technote.authors.affiliations]]
name = "National Astronomical Observatory of Japan"
internal_id = "NAOJ-Chile"
address = "Chile Observatory, Los Abedules 3085, Vitacura, Santiago, Chile"
ror = "https://ror.org/052rrw050"
[[technote.authors]]
internal_id = "schuttt"
name = {given = "Theo", family = "Schutt"}
orcid = "https://orcid.org/0000-0002-7187-9628"

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC-Kavli"
ror = "https://ror.org/00pwqz914"
[[technote.authors]]
internal_id = "liangs"
name = {given = "Shuang", family = "Liang"}

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
ror = "https://ror.org/05gzmn429"
[[technote.authors]]
internal_id = "marshalls"
name = {given = "Stuart", family = "Marshall"}

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC-Kavli"
ror = "https://ror.org/00pwqz914"
[[technote.authors]]
internal_id = "johnsonas"
name = {given = "Anthony S.", family = "Johnson"}
orcid = "https://orcid.org/0000-0002-5729-2716"

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
ror = "https://ror.org/05gzmn429"
[[technote.authors]]
internal_id = "tethersa"
name = {given = "Stephen A.", family = "Tether"}

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
ror = "https://ror.org/05gzmn429"
[[technote.authors]]
internal_id = "constanzocordovaje"
name = {given = "Julio Eduardo", family = "Constanzo Córdova"}
orcid = "https://orcid.org/0009-0004-0368-0643"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory"
internal_id = "RubinObsC"
ror = "https://ror.org/048g3cy84"
